stages:
  - build
  - deploy

workflow:
  rules:
    # Prevent branch pipelines if an MR is open on the branch.
    - if: $CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS
      when: never
    # Allow merge request pipelines.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Build tags and branches too
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

image: kdeorg/staticweb:latest

#deploy_website:
#  tags:
#    - Linux
#  rules:
#    - if: ($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web") && $CI_COMMIT_BRANCH == "master"
#  stage: deploy
#  variables:
#    GIT_STRATEGY: none
#  before_script:
#    - eval $(ssh-agent -s)
#    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#    - mkdir -p ~/.ssh
#    - chmod 700 ~/.ssh
#  script:
#    - rsync -Hrlpvc -e 'ssh -o StrictHostKeyChecking=no' --delete public/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"
