# Dependencies which are needed by the library all the time,
# both, when building and when using. In CMake terminology,
# such dependencies are PUBLIC
Dependencies: {}

# Dependencies which are needed only when the library is used,
# they are not needed when building the project. In CMake
# terminology, such dependencies are INTERFACE
RuntimeDependencies: {}

# Dependencies which are used for the build stage only,
# they are not needed when the library is used. In CMake
# terminology, such dependencies are PRIVATE
BuildDependencies: {}

Environment:
  KDECI_BUILD: "TRUE"

PostInstallScripts: {}

Options:
  in-source-build: False
  use-ccache: False
  ccache-large-cache: False
  cmake-options: ''
  force-ninja-on-windows: True
  release-build: False
  test-before-installing: False
  run-tests: True
  build-tests: True
  tests-load-sensitive: False
  tests-run-in-parallel: False
  per-test-timeout: 60
  setup-x-environment: True
  setup-dbus-session: True
  force-inject-asan: False
  ctest-arguments: ''
  require-passing-tests-on: []
  run-cppcheck: True
  cppcheck-arguments: '--enable=warning,style,performance'
  cppcheck-ignore-files: []
  run-gcovr: True
  gcovr-arguments: ''
  use-asan: True
  pkg-config-sanity-check: 'none' # 'none', 'warning', 'error'
  # Override the 'build' target of the project. The option can be overridden
  # by KDECI_BUILD_TARGET environment variable.
  force-build-target: ''
  # Override the 'install' target of the project. The option can be overridden
  # by KDECI_INSTALL_TARGET environment variable.
  force-install-target: ''
